FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends icecast2 wget \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /var/log/icecast2 \
    && chown icecast2:icecast /var/log/icecast2

COPY config/icecast.xml.example /etc/icecast2/icecast.xml

EXPOSE 8000

USER icecast2
CMD ["icecast2", "-c", "/etc/icecast2/icecast.xml"]
